### ISSUE TITLE
Конкурентный доступ к памяти

### ISSUE THREAD

**Issue by vporoshok** [kcasctiv/rtbpm#1]
В текущей реализации есть конкурентная запись данных. Для проверки можно погонять через go run с флагом -race. К каким аномалиям может привести подобная гонка? Как её исправить?

**Comment by kcasctiv** [comment]
Упс, действительно. Аномалии - неверная итоговая сумма. Исправить можно несколькими способами на самом деле. Сейчас один запушу.

**Comment by kcasctiv** [comment]
Решение: cacffa8c7556f10a5007badee136ce038d22481b

**Comment by vporoshok** [comment]
Да, всё отлично
